package frog.mobile.android

import android.content.Context
import com.google.adk.kt.agents.Instruction
import com.google.adk.kt.agents.LlmAgent
import com.google.adk.kt.litertlm.LiteRtLmModel

/**
 * ADK integration sketch for the first local agent.
 *
 * `generatedTools()` is generated by ADK Kotlin's KSP @Tool processor.
 */
object FrogAgent {
    fun create(model: LiteRtLmModel, context: Context): Pair<LlmAgent, FrogDeviceTools> {
        val tools = FrogDeviceTools(context = context, modelId = model.name)
        val agent = LlmAgent(
            name = "frog_mobile",
            model = model,
            instruction = Instruction(
                """
                You are FROG Mobile, a local Android agent.
                When the user asks to turn the flashlight on or off, call set_flashlight.
                Never claim an action succeeded merely because execution was attempted.
                Report the verification field returned by the tool. If it is CONTRADICTED,
                FAILED, or INDETERMINATE, say that the requested state was not verified.
                """.trimIndent(),
            ),
            tools = tools.generatedTools(),
        )
        return agent to tools
    }
}
